name: Publish Docs

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      # Give the GITHUB_TOKEN write permission to commit and push the
      # changes made to switcher.json.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }} # Checkout branch to allow pushing changes

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        pushd docs
        make clean html linkcheck
        popd

    - name: Update switcher.json and latest version
      if: ${{ github.event_name == 'release' }}
      run: |
        URL="https://python-visualization.github.io/folium/${{ github.ref_name }}"
        echo "Updating latest version to $URL"
        jq '(.[] | select(.version == "latest") | .url) |= "'$URL'"' switcher.json | sponge switcher.json
        echo "Adding ${{ github.ref_name }} entry to switcher.json at index 2 (right after latest)"
        jq '.[2] |= . + {"version": "'${{ github.ref_name }}'", "url": "'$URL'"}' switcher.json | sponge switcher.json

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update switcher.json to ${{ github.ref_name }}
        branch: ${{ github.head_ref }}
        

    - name: Publish to Github Pages on main
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: dev
        keep_files: false

    - name: Publish to Github Pages on release
      if: ${{ github.event_name == 'release' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: ${{ github.ref_name }}
